language: python

python:
    - '3.6'

install:
  - pip install -r requirements-dev.txt -r requirements.txt -e .

script:
  - py.test --cov=vogue -rsxv tests/* 

after_success: coveralls

notifications:
  email: false

