name: build and push docker containers

# Tigger building and testing container 

on:
  push:
    branches-ignore:
      - master
      - develop
    tags-ignore:
      - "**"
    paths:
      - 'Dockerfile'

jobs:
  main:
    name: Docker image build push 
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get branch name
        id: get_branch_name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
      - name: Login to DockerHub
        id: docker_login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build only
        id: docker_build_test
        push: false
        uses: docker/build-push-action@v2
        file: ./Dockerfile
        with:
          push: true
          tags: clinicalgenomics/vogue:${{ steps.get_branch_name.outputs.branch }}
