name: PyTest and CodeCov

on: ["push", "pull_request"]

jobs:
  pytest_coveralls:
    name: run PyTest
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false 
      matrix: 
        python-version: [3.6]

    steps:
      # Checkout Vogue 
      - name: Git checkout
        uses: actions/checkout@v2

      # Setup Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Set up mongodb
      - name: Start MongoDB
        uses: wbari/start-mongoDB@v0.2
        with:
          mongoDBVersion: ${{ matrix.mongodb-version}}

      # Install Vogue 
      - name: Install Vogue 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt 
          # pip install pytest>=3.7.1 pytest-cov==2.8.1 pytest-flask
          pip install -e .

      # Run PyTest
      - name: Run PyTest
        run: |
          py.test --cov-report=xml --cov=vogue -rsxv tests/*

      # Run Codecov 
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
