name: PyTest and CodeCov

on: ["push", "pull_request"]

jobs:
  pytest_coveralls:
    name: run PyTest
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false 
      matrix: 
        python-version: [3.6]

    steps:
      # Checkout Vogue 
      - name: Git checkout
        id: git_checkout
        uses: actions/checkout@v2

      # Get branch name
      - name: Get branch name
        id: get_branch_name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"

      # Install Vogue 
      - name: Install Vogue 
        id: install_vogue
        run: |
          pip install --no-cache-dir -r requirements-dev.txt -r requirements.txt
          pip install -e .

      # Run PyTest
      - name: Run PyTest
        id: pytest
        run: |
          py.test --cov-report=xml --cov=BALSAMIC -rsxv tests/*

      # Run Codecov 
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
